language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  #- hhvm # on Trusty only
  #- nightly

services:
  - docker

before_install:
  - docker pull -t teemops/phpawsapi .
  - docker run -d -p 127.0.0.1:80:8001


