language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  #- hhvm # on Trusty only
  #- nightly

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source

script:
  - ./vendor/bin/phpunit
