language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  #- hhvm # on Trusty only
  #- nightly

services:
  - docker

before_install:
  - docker build -t teemops/phpawsapi .
  - docker run -d -p 127.0.0.1:8081:8081 teemops/phpawsapi
  - npm install -g newman

scripts:
  - newman run tests/postman/collection.json -e tests/postman/travisci.json


