language: php

services:
  - docker

before_install:
  - docker build -t teemops/phpawsapi .
  - docker run -d -p 127.0.0.1:8081:8081 teemops/phpawsapi
  - npm install -g newman

script: composer test


