---

#Appspec for AWS Code Deploy
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
  # AfterInstall:
  #   - location: /srv/apps/api/scripts/restart.sh
  #     timeout: 180
#  ApplicationStart:
#    - location: Scripts/RunFunctionalTests.sh
#      timeout: 3600
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser